export enum Token {
  DOJ = "DOJ",
  USDC = "USDC",
  ETH = "ETH",
  AVAX = "AVAX",
  BNB = "BNB",
  BTC = "BTC",
  DOT = "DOT",
  SOL = "SOL",
  Cosmos = "Atom",
  Hermes = "D11K",
  Arthera = "AA",
  BeraChain = "BERA",
  Empty = "EMPTY",
}
